DATASET:
    train_list: ['PW3D', 'MPII3D', 'Human36M']
    test_list: ['PW3D']
    input_joint_set: 'coco'
    target_joint_set: 'human36'
    workers: 8
    use_gt_input: False
    seqlen: 16
    stride: 1

MODEL:
    name: 'ARTS'
    hpe_dim: 256
    hpe_dep: 3
    joint_dim: 64
    vertx_dim: 64
    normal_loss_weight: 0.1
    edge_loss_weight: 20
    joint_loss_weight: 0.001
    shape_loss_weight: 0.06
    pose_loss_weight: 0.06
    posenet_pretrained: True
    posenet_path: './experiment/exp_03-01_16_10/checkpoint/best.pth.tar'   # 16frame
    # posenet_path: './experiment/exp_03-07_10_36/checkpoint/best.pth.tar'   # 2frame
    # posenet_path: './experiment/exp_03-07_10_38/checkpoint/best.pth.tar'   # 4frame
    # posenet_path: './experiment/exp_03-07_21_29/checkpoint/best.pth.tar'   # 8frame
    # posenet_path: './experiment/exp_03-08_09_52/checkpoint/best.pth.tar'   # 32frame
    

TRAIN:
    print_freq: 20
    batch_size: 16
    shuffle: True
    begin_epoch: 1
    end_epoch: 30
    edge_loss_start: 2
    scheduler: 'step'
    lr: 0.00003
    lr_step: [2, 4, 6, 8, 10, 12, 15, 23]
    lr_factor: 0.9
    optimizer: 'adam'
    wandb: True

TEST:
    batch_size: 64
    shuffle: False